---
title: "How to use 'communities' package" 
output: pdf
---

# scope

```{r libraries, message=FALSE, warning=FALSE}
library(tidyverse)
library(igraph)
library(communities)
```


# examples
## create a ring of cliques

```{r sample1, message=FALSE, warning=FALSE}
g <- communities::make_ring_of_cliques(num_cliques = 4,
                                       clique_size = 6, 
                                       add_center = T, 
                                       add_bridges = T)
plot(g)


```


## explore solutions space
```{r}



sol_space <- communities::solutions_space(g, 
                                          n_trials = 100,
                                          shuffle = TRUE,
                                          met = "IM", 
                                          IM.nb.trials = 1,
                                          confidence = 0.95,  
                                          comp_method = "ami")

sol_space <- communities::quality_check(g, sol_space)
plot_sol_space(sol_space)

df <- sol_space$data
M <- sol_space$M 
plot(make_clusters(g, M[,1]),g)
plot(make_clusters(g, M[,2]),g)
plot(make_clusters(g, M[,3]),g)
plot(make_clusters(g, M[,4]),g)


 
sm <- sol_space$simil
print(paste("non valid solutions: ",sum(df$valid==FALSE)))
print(paste("valid solutions: ",sum(df$valid==TRUE)))

#sol_space$data <- sol_space$data %>% filter(valid == TRUE)


sim_score_solutions <- rowMeans(sol_space$simil, na.rm = T)
print(sim_score_solutions)

overall_similarity<-mean(sol_space$simil, na.rm = T)
print(paste("Mean similarity score = ", overall_similarity))

 
```

 

  

```{r}
g <- communities::make_ring_of_cliques(num_cliques = 10,
                                       clique_size = 5, 
                                       add_center = T, 
                                       add_bridges = F)
ssp <- communities::solutions_space(g, n_trials = 20, met = "WT", confidence = .9) 
ssp <- communities::quality_check(g, ssp)

ssp$data
#ssp$M
plot_sol_space(ssp)
```


```{r}
communities::solutions_space(g, n_trials = 100, met = "WT",  comp_method = "ari", confidence = 0.95) %>% 
  plot_sol_space()

  

```

```{r}
ssp1 <- communities::solutions_space(g, n_trials = 20, met = "LD", resolution = 0.9, comp_method = 'ami')
ssp2 <- communities::solutions_space(g, n_trials = 20, met = "LD", resolution = 0.9, comp_method = 'ari') 

ssp1$data
ssp2$data

```


```{r}
plot(g)
ssp<-communities::solutions_space(g, n_trials = 100, met = "WT", comp_method = "ami") 
plot_sol_space(ssp)
sim_score_solutions <- rowMeans(ssp$simil, na.rm = T)
print(sim_score_solutions)

overall_similarity<-mean(ssp$simil, na.rm = T)
print(paste("Mean similarity score = ", overall_similarity))

```

```{r}
random_graph <- erdos.renyi.game(100, p=0.5, type = "gnp")
V(random_graph)$name <- 1:vcount(random_graph)


random_ssp <- communities::solutions_space(random_graph, n_trials = 50, met = "LD", 
                                           comp_method = "ami", confidence = .9)
random_ssp <- communities::quality_check(random_graph, random_ssp)

df<-random_ssp$data
print(paste("non valid solutions: ",sum(df$valid==FALSE)))
print(paste("valid solutions: ",sum(df$valid==TRUE)))
 
plot_sol_space(random_ssp)

sim_score_solutions <- rowMeans(random_ssp$simil, na.rm = T)
print(sim_score_solutions)

overall_similarity<-mean(random_ssp$simil, na.rm = T)
print(paste("Mean similarity score = ", overall_similarity))


```
```{r}

bayesian_update_1 <- function(prior, i){
    posterior <- prior
    # n increases by 1, hence b increases by 1 for all
    posterior$b <- prior$b + 1
    # except for the i-th element 
    posterior$b[i] <- prior$b[i]  
    
    # k increases by 1 only for the ith element
    posterior$a <- prior$a
    posterior$a[i] <- posterior$a[i] + 1  
    
    return(posterior)
}

bayesian_new_1 <- function(prior){
    n = prior$a[1] + prior$b[1]-2
    print(n)
    posterior <- rbind(prior, data.frame(a = 2, b = n))
    return(posterior)
}

prior <- data.frame(a = 1, b = 1) # no trials, no info
posterior <- bayesian_update_1(prior, i=1)

i=1
posterior <- bayesian_update_1(posterior, i)

posterior <- bayesian_new_1(posterior)

i=4
posterior <- bayesian_update_1(posterior, i)

posterior <- bayesian_new_1(posterior)
```
 

